services:
  raceday:
    build: ./client
    container_name: raceday
    restart: unless-stopped
    ports:
      - '3444:3000'
    environment:
      - NODE_ENV=${NODE_ENV:-production}
    env_file:
      - ${ENV_FILE:-./client/.env.local}
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/api/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
