version: "3"
services:
  client:
    build:
      context: ./client
    ports:
      - "3001:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5001/api
      - NODE_ENV=test
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules
  server:
    build:
      context: ./server
    ports:
      - "5001:5000"
    environment:
      - REACT_APP_API_URL=http://localhost:5001/api
      - NODE_ENV=test
    volumes:
      - ./server:/app
      - /app/node_modules
