name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: ./client/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Run type checking
        run: npx tsc --noEmit

      - name: Run tests
        run: npm test

      - name: Run linter
        run: npm run lint

      - name: Build application
        run: npm run build

  backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server/appwrite

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: ./server/appwrite/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Validate function configuration
        run: |
          echo "Validating Appwrite function configuration..."
          test -f appwrite.json && echo "✓ appwrite.json exists" || exit 1
          test -f functions/daily-race-importer/src/main.js && echo "✓ daily-race-importer main.js exists" || exit 1
          test -f functions/daily-race-importer/package.json && echo "✓ daily-race-importer package.json exists" || exit 1
          test -f functions/race-data-poller/src/main.js && echo "✓ race-data-poller main.js exists" || exit 1
          test -f functions/race-data-poller/package.json && echo "✓ race-data-poller package.json exists" || exit 1
          echo "✓ Function structure validated"

      - name: Check daily-race-importer dependencies
        run: |
          cd functions/daily-race-importer
          npm install
          echo "✓ daily-race-importer dependencies installed successfully"

      - name: Check race-data-poller dependencies
        run: |
          cd functions/race-data-poller
          npm install
          echo "✓ race-data-poller dependencies installed successfully"

      - name: Validate JavaScript syntax
        run: |
          echo "Validating daily-race-importer..."
          cd functions/daily-race-importer
          node -c src/main.js && echo "✓ daily-race-importer main.js syntax valid" || exit 1
          node -c src/database-setup.js && echo "✓ daily-race-importer database-setup.js syntax valid" || exit 1
          cd ../race-data-poller
          echo "Validating race-data-poller..."
          node -c src/main.js && echo "✓ race-data-poller main.js syntax valid" || exit 1
          echo "✓ JavaScript syntax validation completed"
