name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: ./client/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Run type checking
        run: npx tsc --noEmit

      - name: Run tests
        run: npm test

      - name: Run linter
        run: npm run lint

      - name: Build application
        run: npm run build

  backend-daily-entrants:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server/daily-entrants
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.jsS
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: ./server/daily-entrants/package-lock.json
      - name: Validate function configuration
        run: |
          test -f appwrite.json && echo "✓ appwrite.json exists" || exit 1
          test -f src/main.js && echo "✓ main.js exists" || exit 1
          test -f package.json && echo "✓ package.json exists" || exit 1
      - name: Install dependencies
        run: npm install
      - name: Validate JavaScript syntax
        run: |
          node -c src/main.js && echo "✓ main.js syntax valid" || exit 1

  backend-daily-meetings:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server/daily-meetings
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: ./server/daily-meetings/package-lock.json
      - name: Validate function configuration
        run: |
          test -f appwrite.json && echo "✓ appwrite.json exists" || exit 1
          test -f src/main.js && echo "✓ main.js exists" || exit 1
          test -f package.json && echo "✓ package.json exists" || exit 1
      - name: Install dependencies
        run: npm install
      - name: Validate JavaScript syntax
        run: |
          node -c src/main.js && echo "✓ main.js syntax valid" || exit 1

  backend-daily-races:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server/daily-races
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: ./server/daily-races/package-lock.json
      - name: Validate function configuration
        run: |
          test -f appwrite.json && echo "✓ appwrite.json exists" || exit 1
          test -f src/main.js && echo "✓ main.js exists" || exit 1
          test -f package.json && echo "✓ package.json exists" || exit 1
      - name: Install dependencies
        run: npm install
      - name: Validate JavaScript syntax
        run: |
          node -c src/main.js && echo "✓ main.js syntax valid" || exit 1

  backend-race-data-poller:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server/race-data-poller
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: ./server/race-data-poller/package-lock.json
      - name: Validate function configuration
        run: |
          test -f appwrite.json && echo "✓ appwrite.json exists" || exit 1
          test -f src/main.js && echo "✓ main.js exists" || exit 1
          test -f package.json && echo "✓ package.json exists" || exit 1
      - name: Install dependencies
        run: npm install
      - name: Validate JavaScript syntax
        run: |
          node -c src/main.js && echo "✓ main.js syntax valid" || exit 1
